services:
  quarkus-backend-1: &quarkus-backend
    image: adrianomoreira86/rinha-de-backend-2025-java-quarkus:latest
    ports:
      - "8081:8080"
      - "9999:8080"
    networks:
      - app
      - payment-processor
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
#          cpus: "0.5"
#          memory: "150MB"
          cpus: "2.5"
          memory: "450MB"

#  quarkus-backend-2: &quarkus-backend
#    ports:
#      - "8082:8080"
#    deploy:
#      resources:
#        limits:
#          cpus: "0.5"
#          memory: "150MB"

#  nginx:
#    image: nginx:latest
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#    depends_on:
#      - quarkus-backend-1
#      - quarkus-backend-2
#    ports:
#      - "9999:9999"
#    deploy:
#      resources:
#        limits:
#          cpus: ".14"
#          memory: "60MB"

  postgres:
    image: postgres:17
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "rinha", "-U", "admin" ]
      interval: 1s
      timeout: 1s
      retries: 10
    networks:
      - app
    ports:
      - "5432:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql:ro
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "190MB"

networks:
  app:
    driver: bridge
  payment-processor:
    external: true